---
- name: Cloning cinder source repository for development
  become: true
  git:
    repo: "{{ cinder_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ cinder_dev_repos_pull }}"
    version: "{{ cinder_source_version }}"
