---
- name: Cloning aodh source repository for development
  become: true
  git:
    repo: "{{ aodh_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ aodh_dev_repos_pull }}"
    version: "{{ aodh_source_version }}"
