---
- name: Cloning ceilometer source repository for development
  become: true
  git:
    repo: "{{ ceilometer_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/ceilometer"
    update: "{{ ceilometer_dev_repos_pull }}"
    version: "{{ ceilometer_source_version }}"
