---
- name: Cloning keystone source repository for development
  become: true
  git:
    repo: "{{ keystone_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ keystone_dev_repos_pull }}"
    version: "{{ keystone_source_version }}"
