---
features:
  - |
    Adds configuration variables ``kolla_enable_tls_internal``,
    ``kolla_internal_fqdn_cert``, and ``kolla_internal_fqdn_cacert`` to
    optionally enable TLS encryption for OpenStack endpoints on the internal
    API network.
