---
features:
  - |
    The settings file ``{{ node_custom_config}}/horizon/custom_local_settings``
    can be used in Horizon to overwrite the default local_settings without
    a need to sync it at image build time.
