---
fixes:
  - |
    Fixes the default CloudKitty configuration, which included the
    ``gnocchi_collector`` and ``keystone_fetcher`` options that were deprecated
    in Stein and removed in Train. See `bug 1876985
    <https://bugs.launchpad.net/kolla-ansible/+bug/1876985>`__ for details.
