---
features:
  - |
    Allow users to set neutron type drivers and tenant network types.
    These are configurable via 'neutron_type_drivers' and
    'neutron_tenant_network_types' variables correspondingly.
    Tenant network types are checked against a list of type drivers.
    Also 'flat' network type is checked in the lists for Ironic.
upgrade:
  - |
    Default neutron_tenant_network_types list consist of 'vxlan'.
    Ironic users should add 'flat' to the list. Also for Hyper-V
    the list should contain 'vlan'.
