---
features:
  - |
    Adds support for configuring vendor info in Nova via the ``release`` file.
    To do this place a file called ``release`` in one of the following
    locations:

    * /etc/kolla/config/nova/release
    * /etc/kolla/config/nova_compute/release
    * /etc/kolla/config/nova_compute/{{ inventory_hostname }}/release

    An example of the file can be seen at
    https://github.com/openstack/nova/blob/master/etc/nova/release.sample
