---
deprecations:
  - |
    The following files are deprecated and should be removed during Queens
    cycle, use ``/etc/kolla/config/global.conf`` instead:

    * /etc/kolla/config/database.conf
    * /etc/kolla/config/messaging.conf
