---
fixes:
  - |
    Adapts Octavia to the latest dual CA certificate configuration. The
    following files should exist in ``/etc/kolla/config/octavia/``:

    * ``client.cert-and-key.pem``
    * ``client_ca.cert.pem``
    * ``server_ca.cert.pem``
    * ``server_ca.key.pem``

    See the `Octavia documentation
    <https://docs.openstack.org/octavia/latest/admin/guides/certificates.html>`__
    for details on generating these files.
