---
features:
  - |
    Adds ability to configure custom fluentd formatting.

    In some scenarios it may be useful to configure custom fluentd formatting
    to, for example, convert events to JSON.

    Configuration of custom fluentd formatting is possible by placing
    output configuration files in /etc/kolla/config/fluentd/format/\*.conf.
