---
features:
  - |
    Adds ability to configure custom fluentd inputs.

    Configuration of custom fluentd inputs is possible by placing
    input configuration files in /etc/kolla/config/fluentd/input/\*.conf.
