---
features:
  - |
    Adds ability to configure custom fluentd outputs.

    In some scenarios it may be useful to configure custom fluentd outputs
    to forward logs to a logging service other than elasticsearch.

    Configuration of custom fluentd outputs is possible by placing
    output configuration files in /etc/kolla/config/fluentd/output/\*.conf.
