---
features:
  - |
    Adds support for managing Ceilometer dynamic pollster configuration in
    Kolla Ansible. This feature will look for configurations in
    ``{{ node_custom_config }}/ceilometer/pollster.d/`` by default.
    If there are configs there, they are copied to the control nodes,
    to configure Ceilometer dynamic pollster sub-system.
