---
fixes:
  - |
    Fixes an issue where host configuration tasks (``sysctl``, loading kernel
    modules) could be performed during the ``kolla-ansible genconfig`` command.
    See `bug 1860161 <https://bugs.launchpad.net/kolla-ansible/+bug/1860161>`__
    for details.
