---
upgrade:
  - |
    The Heat role has stopped disabling deprecated plugins. To apply this
    change to existing deployments, the file
    ``/etc/kolla/heat-engine/_deprecated.yaml`` is automatically removed
    during the upgrade.
