---
upgrade:
  - |
    The following files ``/etc/kolla/config/database.conf`` and
    ``/etc/kolla/config/messaging.conf`` used to generate Openstack services
    files are redundant with ``/etc/kolla/config/global.conf``.
    They have been removed in order to simplify codebase.
