---
features:
  - |
    HAProxy configuration is now split per service, which makes creating and
    updating service configurations much simpler.
upgrade:
  - |
    All HAProxy-related variables have been moved from the ``haproxy`` role to
    the ``haproxy-common`` role, with the exception of the following which were
    also split and renamed after the move\:

    * ``haproxy_listen_tcp_extra`` becomes ``haproxy_frontend_tcp_extra`` and
      ``haproxy_backend_tcp_extra``
    * ``haproxy_listen_http_extra`` becomes ``haproxy_frontend_http_extra`` and
      ``haproxy_backend_http_extra``
  - |
    The following additional haproxy related variables have been created in the
    ``haproxy-common`` role\:

    * ``haproxy_http_request_timeout``\: default http request timeout for
      haproxy
    * ``haproxy_queue_timeout``\: default queue timeout for haproxy
    * ``haproxy_connect_timeout``\: default connect timeout for haproxy
    * ``haproxy_check_timeout``\: default check timeout for haproxy
    * ``haproxy_health_check``\: default health check string for haproxy
    * ``haproxy_service_template``\: select which haproxy config style to use
