---
upgrade:
  - |
    Neutron Linux bridge and Open vSwitch Agents config has been split out into
    ``linuxbridge_agent.ini`` and ``openvswitch_agent.ini`` respectively.
    Please move your custom service config from ``ml2_conf.ini`` into those
    files.
deprecations:
  - |
    Customizing Neutron Linux bridge and Open vSwitch Agents config via
    ``ml2_conf.ini`` is deprecated. The config has been split out for these
    agents into ``linuxbridge_agent.ini`` and ``openvswitch_agent.ini``
    respectively. In this release (Ussuri) custom service config
    ``ml2_conf.ini`` overrides will still be used when merging configs - but
    but that functionality will be removed in the Victoria release.
