---
features:
  - |
    Adds support for Ansible check and diff mode when generating configuration.
    It is possible to use ``EXTRA_OPTS='--check --diff' kolla-ansible
    genconfig`` to check what the configuration file will be like in dry-run
    mode.
