---
upgrade:
  - |
    The  default value of ``REST_API_REQUIRED_SETTINGS`` was synchronized with
    Horizon. You may want to review settings exposed by the `updated
    configuration
    <https://docs.openstack.org/horizon/latest/configuration/settings.html#rest-api-required-settings>`__.
fixes:
  - |
    Updates the default value of ``REST_API_REQUIRED_SETTINGS`` in Horizon
    ``local_settings``, which enables some features such as `selecting the
    default boot source for instances
    <https://docs.openstack.org/horizon/latest/configuration/settings.html#default-boot-source>`__.
    `LP#1891024 <https://launchpad.net/bugs/1891024>`__
