---
prelude: >
  The Kolla Ansible ``9.0.0`` release is the first release in the Train cycle.
  Highlights include support for deployment of the Masakari instance High
  Availability service and Qinling Function as a Service. It is now possible
  to deploy multiple Nova cells, and the control plane may be configured to
  communicate via IPv6.
