---
- name: Cloning senlin source repository for development
  become: true
  git:
    repo: "{{ senlin_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ senlin_dev_repos_pull }}"
    version: "{{ senlin_source_version }}"
