---
- name: Cloning watcher source repository for development
  become: true
  git:
    repo: "{{ watcher_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ watcher_dev_repos_pull }}"
    version: "{{ watcher_source_version }}"
