---
- name: Cloning nova source repository for development
  become: true
  git:
    repo: "{{ nova_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ nova_dev_repos_pull }}"
    version: "{{ nova_source_version }}"
