---
- name: Cloning magnum source repository for development
  become: true
  git:
    repo: "{{ magnum_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ magnum_dev_repos_pull }}"
    version: "{{ magnum_source_version }}"
