---
- name: Cloning vitrage source repository for development
  become: true
  git:
    repo: "{{ vitrage_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ vitrage_dev_repos_pull }}"
    version: "{{ vitrage_source_version }}"
