---
- name: Cloning kuryr source repository for development
  become: true
  git:
    repo: "{{ kuryr_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ kuryr_dev_repos_pull }}"
    version: "{{ kuryr_source_version }}"

- name: Cloning kuryr-libnetwork source repository for development
  become: true
  git:
    repo: "{{ kuryr_libnetwork_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ libnetwork_project_name }}"
    update: "{{ kuryr_dev_repos_pull }}"
    version: "{{ kuryr_source_version }}"
