---
- name: Cloning source repositories for development
  become: true
  git:
    repo: "{{ tacker_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ tacker_dev_repos_pull }}"
    version: "{{ tacker_source_version }}"
