---
- name: Cloning solum source repository for development
  become: true
  git:
    repo: "{{ solum_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ solum_dev_repos_pull }}"
    version: "{{ solum_source_version }}"
