---
- name: Load and persist configfs module
  import_role:
    name: module-load
  vars:
    modules:
      - name: configfs
  when:
    - inventory_hostname in groups[iscsi_services.iscsid.group]
    - iscsi_services.iscsid.enabled | bool
