---
- name: Redis ping pong check
  become: true
  command: "docker exec redis redis-cli -h {{ api_interface_address }} -a {{ redis_master_password }} ping"
  register: redis_check
  changed_when: "redis_check.stdout != 'PONG'"
  failed_when: "redis_check.stdout != 'PONG'"
