---
- name: Cloning octavia source repository for development
  become: true
  git:
    repo: "{{ octavia_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ octavia_dev_repos_pull }}"
    version: "{{ octavia_source_version }}"
